List command mostly fixed
error on ftp_server.py:

line 33, in threaded
    data_connection.send(size_of_data.to_bytes(4, byteorder='big', signed=False))
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied